### ISSUE TITLE
Serial commands reading issue :) 

### ISSUE THREAD

**Issue by bilalh96** [makerspacelt/fz35-cli#2] opened 2021-07-23 13:08 UTC
Firstly, thanks for doing a Cli project for this device. I am interested in doing a small script in python but with some other funtions . my script works but I am finding issues with the serial commands for  when I do 'read' , I get sometimes battery parameters too and not protections and vice versa. I want to know if there any specific bytes to be used in serial.readlines method or sleep should be extended? 
btw I am using pyserial package and usb ttl converter as an adapter to my laptop. if you are willing to help then I can tell a bit more detail about the issue , would be grateful for your support 👍🏽 

Kind regards,

**Comment by dariuskt** [comment] 2021-08-01 10:07
My implementation is in bash, so not sure about python. And also I use TCP on esp8266 via esp-link for communication so timings and buffering can be different. My code was intended to be portable with minimal dependencies and not particularly fast or robust. So I solved most of the timing issues with simple sleep.

As this does not look like an issue with my code I gonna close it.

**Closed as completed by dariuskt** 2021-08-01 10:07 UTC
